name: Build & release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    strategy:
      matrix:
        include:
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest  

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
      
      - name: Build release
        run: cargo build --no-default-features --release

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "target/release/app"
          allowUpdates: true
          draft: true
          generateReleaseNotes: true