[workspace]
members = [
    "warp-api",
    "repository",
    "domain",
    "types",
    "redis",
    "search",
    "axum-api",
    "server",
]

[profile.dev]
codegen-units = 16

[profile.release]
lto = true
opt-level = 'z'
