[package]
name = "rust-sqlx-warp-server"
version = "0.1.0"
edition = "2018"
autotests = false

[[bin]]
bench = false
path = "server/src/main.rs"
name = "app"

[dependencies]
api = { path = "./api", features = ["postgres"] }
async-trait = "0.1"
flexi_logger = "0.19.3"
log = "0.4"
dotenv = "0.15.0"
tokio = { version = "1", features = ["macros"] }

[workspace]
members = ["api", "repository", "domain", "types"]
