[package]
name = "repository"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

[lib]
name = "repository"
path = "src/lib.rs"

[dependencies]
types = { path = "../types", features = ["postgres"] }
sqlx = { version = "0.5", default-features = false, features = [
    "runtime-tokio-rustls",
    "macros",
    "chrono",
] }
serde = { version = "1.0.125", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
anyhow = "1.0.40"
async-trait = "0.1"
flexi_logger = "0.19.3"
log = "0.4"
async_once = "0.2.1"
sql-builder = "3.1.1"
lazy_static = "1.4.0"